const $=id=>document.getElementById(id);
const worker=new Worker('./worker.js');let requestId=0;const pending=new Map();
worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);clearTimeout(p.timer);data.result.ok?p.resolve(data.result):p.reject(Error(data.result.error));};
worker.onerror=()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Database engine failed to load. Reload to retry.'));}pending.clear();};
function call(action,payload={}){return new Promise((resolve,reject)=>{const id=++requestId;const timer=setTimeout(()=>{pending.delete(id);reject(Error('Database operation timed out. Reload to retry.'));},60000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,action,...payload});});}
let scenarios=[],selected,step=0,state,history=[],busy=false,customCount=0;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function explainState(result){
  const hasAnswer=Boolean(result?.targets?.some(t=>t.id===result.answer));
  if(result?.status==='resolved')return {label:'Resolved',title:'Enough independent support',body:"The current answer meets this demo's configured support policy."};
  if(result?.status==='contested')return {label:'Contested',title:'A leading answer exists, but contradiction remains',body:'MoolBase keeps the leading answer visible while preserving material opposing evidence.'};
  if(!hasAnswer)return {label:'Evidence required',title:'More evidence required',body:'MoolBase does not yet have enough independent evidence to select an operative answer.'};
  if(result?.status==='provisionally_resolved')return {label:'Provisional',title:'Leading answer, not fully resolved',body:'A candidate leads, but the configured resolution policy has not been fully satisfied.'};
  return {label:String(result?.status||'Open').replaceAll('_',' '),title:'Governed intermediate state',body:'Inspect the evidence and technical details before treating this state as resolved.'};
}
function controls(){for(const id of ['next','run','reset','reopen','download','custom-submit'])$(id).disabled=busy||!state||(id==='next'||id==='run')&&step>=selected.events.length;document.querySelectorAll('#scenarios button').forEach(b=>b.disabled=busy);$('engine-status').textContent=busy?'Evaluating…':'Engine ready';$('progress').textContent=`${step} / ${selected?.events.length||0} guided events`; $('next-text').textContent=selected?.events[step]?.content||'Scenario complete. Add custom evidence or inspect the receipt.';}
async function perform(fn){if(busy)throw Error('An operation is already running');busy=true;controls();$('message').textContent='';try{return await fn();}catch(e){$('message').textContent=e.message;throw e;}finally{busy=false;controls();}}
function render(result,observation){const previous=state;const label=r=>r?.targets.find(t=>t.id===r.answer)?.content||'No operative answer';if(observation){const target=result.targets[observation.target];const before=previous?.targets[observation.target]?.families||0;$('change-summary').textContent=`${label(previous)} → ${label(result)}. Status: ${previous?explainState(previous).label:'Evidence required'} → ${explainState(result).label}. Stored ${observation.kind} from ${observation.family}. Independent support families for this target: ${before} → ${target.families}.`;}else{$('change-summary').textContent=result.evidence.length?'Database replay complete. Compare the answer, status and evidence receipt.':'Start with Add next evidence. Watch how independent sources, copied reports and corrections affect the answer.';}state=result;history.push(result);const stateView=explainState(result);$('status').textContent=stateView.label;$('status').className='status '+result.status;const answer=result.targets.find(t=>t.id===result.answer);$('answer').textContent=answer?answer.content:'No operative answer';$('state-explanation').innerHTML=`<strong>${escape(stateView.title)}</strong><span>${escape(stateView.body)}</span>`;$('snapshot').textContent=result.snapshot;$('hash').textContent=result.bundleHash;$('visited').textContent=result.visitedStates;
 $('targets').innerHTML=result.targets.map(t=>`<div class="target ${t.id===result.answer?'selected':''}"><p class="eyebrow">${t.id===result.answer?'OPERATIVE ANSWER':'ALTERNATIVE'}</p><strong>${escape(t.content)}</strong><div class="score-row"><span>Independent support families</span><b>${t.families}</b></div><div class="score-row"><span>Support strength</span><b>${t.support.toFixed(3)}</b></div><div class="bar"><span style="width:${Math.max(0,Math.min(100,t.support*100))}%"></span></div><div class="score-row"><span>Opposition strength</span><b>${t.opposition.toFixed(3)}</b></div></div>`).join('');
 const diagnosticItems=[...result.uncertainty,...(result.truncated?['Retrieval reached its configured bound.']:[])];$('uncertainty').innerHTML=diagnosticItems.length?`<ul>${diagnosticItems.map(x=>`<li>${escape(x)}</li>`).join('')}</ul>`:'<p class="helper">No additional diagnostics.</p>';
 $('events').innerHTML=result.events.map(e=>`<div class="event"><span>${escape(e.type.replaceAll('_',' '))}</span><p>${escape(e.reason)}</p></div>`).join('')||'<p class="helper">No native events returned.</p>';
 $('evidence').innerHTML=result.evidence.map(e=>`<tr class="${e.state==='active'?'':'retired'}"><td>${escape(e.content)}<small>${escape(e.id)}</small></td><td>${escape(e.family.replace(/^family:/,''))}</td><td>${escape(e.kind)}</td><td>${e.verified?'Supplied verified':'Unverified'}</td><td>${escape(e.state)}</td></tr>`).join('')||'<tr><td colspan="5">No observations stored yet.</td></tr>';
 const previousTarget=$('custom-target').value; $('custom-target').innerHTML=result.targets.map((t,i)=>`<option value="${i}">${escape(t.content)}</option>`).join('');if(previousTarget==='0'||previousTarget==='1')$('custom-target').value=previousTarget;const old=$('custom-retire').value;$('custom-retire').innerHTML='<option value="">None</option>'+result.evidence.filter(e=>e.state==='active').map(e=>`<option value="${escape(e.id)}">${escape(e.id)}</option>`).join('');$('custom-retire').value=result.evidence.some(e=>e.id===old&&e.state==='active')?old:'';$('session-capacity').textContent=`${result.capacity.active} / ${result.capacity.maxActive} active observations · ${result.capacity.events} / ${result.capacity.maxEvents} history events. Revocation and supersession remain available at the active limit.`;controls();
}
async function selectScenario(id){const s=scenarios.find(x=>x.id===id);if(!s)throw Error('Unknown scenario');return perform(async()=>{const result=await call('reset',{hypotheses:s.hypotheses});selected=s;step=0;history=[];state=undefined;customCount=0;document.querySelectorAll('#scenarios button').forEach(b=>b.classList.toggle('active',b.dataset.id===id));for(const key of ['category','question','description','when','alternative'])$(key).textContent=s[key];render(result);return state;});}
async function nextEvidence(){if(step>=selected.events.length)throw Error('Scenario complete');return perform(async()=>{const r=await call('add',{event:selected.events[step]});const observation=selected.events[step];step++;render(r,observation);return r;});}
async function runAll(){return perform(async()=>{while(step<selected.events.length){const r=await call('add',{event:selected.events[step]});const observation=selected.events[step];step++;render(r,observation);}return state;});}
$('next').onclick=()=>nextEvidence().catch(()=>{});$('run').onclick=()=>runAll().catch(()=>{});$('reset').onclick=()=>selectScenario(selected.id).catch(()=>{});
$('reopen').onclick=()=>perform(async()=>{const before=state;const r=await call('reopen');render(r);$('message').textContent=r.bundleHash===before.bundleHash&&r.answer===before.answer?'Database reopened. File replay preserved the evidence bundle and operative answer.':'Database reopened; inspect the new receipt for changes.';}).catch(()=>{});
$('download').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'moolbase-customer-demo-v1',scenario:selected.id,dataClass:'realistic synthetic replay',persistence:'browser session only',states:history},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`moolbase-${selected.id}-receipt.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('custom-kind').onchange=()=>{$('custom-retire').required=['revoke','supersede'].includes($('custom-kind').value);};
$('custom-form').onsubmit=event=>{event.preventDefault();const f=new FormData(event.target),kind=f.get('kind'),retire=f.get('retire');if(['revoke','supersede'].includes(kind)&&!retire){$('message').textContent='Choose active prior evidence to retire.';return;}if(!['revoke','supersede'].includes(kind)&&retire){$('message').textContent='Choose None for prior evidence when adding support or contradiction.';return;}const e={id:'custom-'+(++customCount),content:f.get('content'),family:f.get('family'),target:Number(f.get('target')),kind,verified:f.has('verified'),retire};perform(async()=>{render(await call('add',{event:e}),e);$('message').textContent='Your evidence was stored and evaluated by MoolBase.';}).catch(()=>{});};
async function initialize(){scenarios=await fetch('./scenarios.json').then(r=>{if(!r.ok)throw Error('Could not load scenarios');return r.json();});$('scenarios').innerHTML=scenarios.map((s,i)=>`<button data-id="${s.id}"><span>0${i+1} / ${escape(s.category)}</span>${escape(s.title)}</button>`).join('');document.querySelectorAll('#scenarios button').forEach(b=>b.onclick=()=>selectScenario(b.dataset.id).catch(()=>{}));await selectScenario(scenarios[0].id);
 if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'run_moolbase_scenario',description:'Reset and run a guided MoolBase evidence scenario, updating the visible ledger and native receipt.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:scenarios.map(s=>s.id)}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||Object.keys(input).length!==1||!scenarios.some(s=>s.id===input.scenario))throw Error('Invalid scenario');await selectScenario(input.scenario);const r=await runAll();return {status:r.status,answer:r.answer,bundleHash:r.bundleHash};}});}catch(e){console.warn('Optional agent tool registration failed',e.message);}}
}
initialize().catch(e=>{$('engine-status').textContent='Unable to start';$('message').textContent=e.message;});
