#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="${BUILD_DIR:-$ROOT/build-release}"
GRAPHENEDB_USE_FAISS_FLAG="${GRAPHENEDB_USE_FAISS:-OFF}"
if [[ "$GRAPHENEDB_USE_FAISS_FLAG" == "1" || "$GRAPHENEDB_USE_FAISS_FLAG" == "true" || "$GRAPHENEDB_USE_FAISS_FLAG" == "TRUE" || "$GRAPHENEDB_USE_FAISS_FLAG" == "on" || "$GRAPHENEDB_USE_FAISS_FLAG" == "ON" ]]; then
  GRAPHENEDB_USE_FAISS_FLAG="ON"
else
  GRAPHENEDB_USE_FAISS_FLAG="OFF"
fi
cmake -S "$ROOT" -B "$BUILD" -DCMAKE_BUILD_TYPE=Release -DGRAPHENEDB_BUILD_TESTS=ON -DGRAPHENEDB_BUILD_BENCH=ON -DGRAPHENEDB_BUILD_EXAMPLES=ON -DGRAPHENEDB_USE_FAISS="$GRAPHENEDB_USE_FAISS_FLAG"
cmake --build "$BUILD" -j"$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)"
echo "Release build complete: $BUILD"
