#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-build-enterprise-target-scale}"
REPORT_DIR="${REPORT_DIR:-reports/enterprise-ga}"
CONFIG="${CONFIG:-Release}"
PROFILE_LABEL="${PROFILE_LABEL:-target-scale-approved}"
APPROVED_HOST="${APPROVED_HOST:-1}"
SOAK_SECONDS="${SOAK_SECONDS:-86400}"
SOAK_DIM="${SOAK_DIM:-384}"
STRESS_INCIDENTS="${STRESS_INCIDENTS:-16667}"
STRESS_QUERIES="${STRESS_QUERIES:-500}"
STRESS_DIM="${STRESS_DIM:-384}"
STRESS_VECTOR_INDEX="${STRESS_VECTOR_INDEX:-auto}"
ONE_M_NODES="${ONE_M_NODES:-1000000}"
ONE_M_QUERIES="${ONE_M_QUERIES:-100}"
ONE_M_DIM="${ONE_M_DIM:-768}"
ONE_M_VECTOR_INDEX="${ONE_M_VECTOR_INDEX:-auto}"
FUZZ_RUNS="${FUZZ_RUNS:-500000}"
FUZZ_BUILD_DIR="${FUZZ_BUILD_DIR:-build-enterprise-target-scale-fuzz}"
FUZZ_CC="${FUZZ_CC:-clang}"
FUZZ_CXX="${FUZZ_CXX:-clang++}"
GRAPHENEDB_USE_FAISS="${GRAPHENEDB_USE_FAISS:-0}"
SKIP_SOAK="${SKIP_SOAK:-0}"
SKIP_GA_READINESS="${SKIP_GA_READINESS:-0}"
SKIP_FULL_CTEST="${SKIP_FULL_CTEST:-0}"
SKIP_FUZZ="${SKIP_FUZZ:-0}"

env \
  BUILD_DIR="$BUILD_DIR" \
  REPORT_DIR="$REPORT_DIR" \
  CONFIG="$CONFIG" \
  PROFILE_LABEL="$PROFILE_LABEL" \
  APPROVED_HOST="$APPROVED_HOST" \
  SOAK_SECONDS="$SOAK_SECONDS" \
  SOAK_DIM="$SOAK_DIM" \
  STRESS_INCIDENTS="$STRESS_INCIDENTS" \
  STRESS_QUERIES="$STRESS_QUERIES" \
  STRESS_DIM="$STRESS_DIM" \
  STRESS_VECTOR_INDEX="$STRESS_VECTOR_INDEX" \
  ONE_M_NODES="$ONE_M_NODES" \
  ONE_M_QUERIES="$ONE_M_QUERIES" \
  ONE_M_DIM="$ONE_M_DIM" \
  ONE_M_VECTOR_INDEX="$ONE_M_VECTOR_INDEX" \
  FUZZ_RUNS="$FUZZ_RUNS" \
  FUZZ_BUILD_DIR="$FUZZ_BUILD_DIR" \
  FUZZ_CC="$FUZZ_CC" \
  FUZZ_CXX="$FUZZ_CXX" \
  GRAPHENEDB_USE_FAISS="$GRAPHENEDB_USE_FAISS" \
  SKIP_SOAK="$SKIP_SOAK" \
  SKIP_GA_READINESS="$SKIP_GA_READINESS" \
  SKIP_FULL_CTEST="$SKIP_FULL_CTEST" \
  SKIP_FUZZ="$SKIP_FUZZ" \
  "$ROOT/scripts/run_enterprise_ga_campaign.sh"
