// npm install playwright@1.51.1 && npx playwright install chromium
// PLAYWRIGHT_MODULE=/absolute/node_modules/playwright/index.mjs node verify_playwright.mjs SITE_DIST
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve(process.argv[2]);let checks=0;const results=[];
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!path.startsWith(root+'/'))throw Error();const data=await readFile(path);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.json':'application/json','.wasm':'application/wasm','.css':'text/css'})[extname(path)]||'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
async function test(name,fn){await fn();checks++;results.push(name);console.log('PASS',name);}
try{
 for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
 const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const Original=Worker;window.Worker=class extends Original{postMessage(data,...args){if(window.failReset&&data.action==='reset'){window.failReset=false;setTimeout(()=>this.dispatchEvent(new MessageEvent('message',{data:{id:data.id,result:{ok:false,error:'Injected reset failure'}}})),0);return;}super.postMessage(data,...args);}};});
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#engine-status').textContent==='Engine ready');
 await test(`guided scenarios ${viewport.width}px`,async()=>{
 const count=await page.locator('#scenarios button').count();assert.equal(count,3);
 for(let i=0;i<count;i++){await page.locator('#scenarios button').nth(i).click();await page.waitForFunction(()=>document.querySelector('#next').disabled===false);await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#run').disabled&&document.querySelector('#engine-status').textContent==='Engine ready');const hash=await page.locator('#hash').textContent();await page.locator('#reopen').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('File replay preserved'));assert.equal(await page.locator('#hash').textContent(),hash);const download=page.waitForEvent('download');await page.locator('#download').click();const d=await download;const payload=JSON.parse(await readFile(await d.path(),'utf8'));assert.equal(payload.states.at(-1).bundleHash,hash);assert(payload.states.length>3);}
 });
 await test(`plain-language duplicate explanation ${viewport.width}px`,async()=>{await page.locator('#scenarios button').first().click();await page.waitForFunction(()=>document.querySelector('#session-capacity').textContent.startsWith('0 /'));await page.locator('#next').click();await page.waitForFunction(()=>document.querySelector('#session-capacity').textContent.startsWith('1 /'));await page.locator('#next').click();await page.waitForFunction(()=>document.querySelector('#session-capacity').textContent.startsWith('2 /'));assert((await page.locator('#change-summary').textContent()).includes('Independent support families for this target: 1 → 1'));});
 await test(`failed reset preserves scenario and receipt ${viewport.width}px`,async()=>{const before=await page.evaluate(()=>({q:document.querySelector('#question').textContent,h:document.querySelector('#hash').textContent,active:document.querySelector('#scenarios .active').dataset.id,rows:document.querySelector('#evidence').textContent}));await page.evaluate(()=>window.failReset=true);await page.locator('#scenarios button').last().click();await page.waitForFunction(()=>document.querySelector('#message').textContent==='Injected reset failure');assert.deepEqual(await page.evaluate(()=>({q:document.querySelector('#question').textContent,h:document.querySelector('#hash').textContent,active:document.querySelector('#scenarios .active').dataset.id,rows:document.querySelector('#evidence').textContent})),before);assert.equal(await page.locator('#reset').isEnabled(),true);});
 await test(`custom evidence lifecycle ${viewport.width}px`,async()=>{await page.locator('#reset').click();await page.waitForFunction(()=>document.querySelector('#session-capacity').textContent.startsWith('0 /'));await page.locator('.custom summary').click();await page.locator('[name=content]').fill('Independent trace');await page.locator('[name=family]').fill('customer-trace');await page.locator('#custom-target').selectOption('1');await page.locator('#custom-submit').click();await page.waitForFunction(()=>document.querySelector('#evidence').textContent.includes('custom-1'));assert.equal(await page.locator('#custom-target').inputValue(),'1');await page.locator('#custom-kind').selectOption('supersede');await page.locator('#custom-retire').selectOption('custom-1');await page.locator('[name=content]').fill('Corrected trace');await page.locator('#custom-submit').click();await page.waitForFunction(()=>document.querySelector('#evidence').textContent.includes('superseded'));assert.equal(await page.locator('#custom-target').inputValue(),'1');});
 await test(`story-first landing narrative ${viewport.width}px`,async()=>{const hero=await page.locator('#hero-title').textContent();assert(hero.includes('Facts don’t arrive finished'));const story=await page.locator('#story').textContent();assert(story.includes('temporal database'));assert(story.includes('converge'));assert(story.includes('diverge'));assert((await page.locator('.thesis-strip').textContent()).includes('Re-converge'));assert((await page.locator('.evolution-section').textContent()).includes('HypoKosh'));assert((await page.locator('.evolution-section').textContent()).includes('DWM'));assert((await page.locator('#how').textContent()).includes('what fact is currently established'));assert.equal(await page.locator('.lab-guide article').count(),3);assert((await page.locator('#future').textContent()).includes('research direction'));const order=await page.evaluate(()=>({story:document.querySelector('#story').getBoundingClientRect().top,lab:document.querySelector('#lab').getBoundingClientRect().top,future:document.querySelector('#future').getBoundingClientRect().top}));assert(order.story<order.lab);assert(order.lab<order.future);});
 await test(`public state language and full architecture ${viewport.width}px`,async()=>{await page.locator('#scenarios button').first().click();await page.waitForFunction(()=>document.querySelector('#engine-status').textContent==='Engine ready');assert.equal(await page.locator('#status').textContent(),'Evidence required');assert((await page.locator('#state-explanation').textContent()).includes('More evidence required'));const architecture=await page.locator('#architecture').textContent();for(const term of ['MoolBase Core','Dense hexagonal lattice','FiberBundle','HypoKosh','DWM','Epistemic receipt'])assert(architecture.includes(term),term);assert.equal(await page.locator('.technical-details').getAttribute('open'),null);});
 await test(`social metadata ${viewport.width}px`,async()=>{const meta=await page.evaluate(()=>({canonical:document.querySelector('link[rel=canonical]')?.href,description:document.querySelector('meta[name="description"]')?.content,ogTitle:document.querySelector('meta[property="og:title"]')?.content,ogImage:document.querySelector('meta[property="og:image"]')?.content,twitter:document.querySelector('meta[name="twitter:card"]')?.content}));assert.equal(meta.canonical,'https://moolbase.rasvai.com/');assert(meta.description.includes('temporal epistemic database'));assert(meta.ogTitle.includes('temporal database'));assert(meta.ogImage.includes('opengraph.githubassets.com'));assert.equal(meta.twitter,'summary_large_image');});
 await test(`sample download and layout ${viewport.width}px`,async()=>{const download=page.waitForEvent('download');await page.locator('a[download]').click();const d=await download;const zip=await readFile(await d.path());assert.equal(zip.subarray(0,2).toString(),'PK');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);});
 await page.screenshot({path:resolve(root,'..',`playwright-${viewport.width}.png`),fullPage:true});await page.close();
 }
 const page=await browser.newPage();await page.goto(url);
 const report=await page.evaluate(async()=>{
 const worker=new Worker('./worker.js');let id=0;const rpc=(action,payload={})=>new Promise(r=>{const n=++id;worker.onmessage=e=>{if(e.data.id===n)r(e.data.result)};worker.postMessage({id:n,action,...payload});});
 const ok=(v,m)=>{if(!v)throw Error(m)};const event=(id,family='f'+id,kind='support',retire='')=>({id,content:'Observation '+id,family,target:0,kind,verified:true,retire});
 await rpc('reset',{hypotheses:['A','B']});await rpc('add',{event:event('first')});const baseline=await rpc('reopen');
 const invalid=[{target:'0'},{target:NaN},{target:.5},{verified:'false'},{content:'prefix\0suffix'},{id:42},{family:'😀'.repeat(21)},{content:' '},{extra:true},{kind:'unknown'},{kind:'support',retire:'first'}];
 for(const patch of invalid){const r=await rpc('add',{event:{...event('bad'),...patch}});ok(!r.ok,'malformed input accepted '+JSON.stringify(patch));const after=await rpc('reopen');ok(after.snapshot===baseline.snapshot&&after.bundleHash===baseline.bundleHash&&after.evidence.length===1,'invalid input mutated database');}
 ok((await rpc('add',{event:{...event('unverified'),verified:false}})).ok,'false certificate rejected');
 await rpc('reset',{hypotheses:['A','B']});for(let i=0;i<3;i++)ok((await rpc('add',{event:event('independent'+i)})).ok,'seed');for(let i=0;i<60;i++)ok((await rpc('add',{event:event('duplicate'+i,'findependent0')})).ok,'duplicate');
 let r=await rpc('add',{event:event('late-contradiction','counter-trace','refute')});ok(r.ok&&r.targets[0].opposition>0&&r.status==='contested'&&!r.truncated,'late contradiction lost');const hash=r.bundleHash;r=await rpc('reopen');ok(r.bundleHash===hash&&r.targets[0].opposition>0,'contradiction lost after reopen');
 for(let i=64;i<100;i++)ok((await rpc('add',{event:event('capacity'+i,'findependent0')})).ok,'capacity fill');r=await rpc('add',{event:event('overflow')});ok(!r.ok&&r.error.toLowerCase().includes('active'),'101st active accepted');r=await rpc('add',{event:event('replace','new','supersede','independent0')});ok(r.ok&&r.capacity.active===100,'supersession at capacity blocked');r=await rpc('add',{event:event('revoke','new','revoke','independent1')});ok(r.ok&&r.capacity.active===99,'revocation at capacity blocked');
 for(let i=102;i<200;i++)ok((await rpc('add',{event:event('revision'+i,'new','supersede',i===102?'replace':'revision'+(i-1))})).ok,'history capacity');r=await rpc('add',{event:event('overhistory','new','revoke','revision199')});ok(!r.ok&&r.error.includes('history'),'unbounded history');r=await rpc('reopen');ok(r.capacity.events===200&&r.capacity.active===99,'history state');worker.terminate();return {invalidCases:invalid.length,lateOpposition:true,activeLimit:100,historyLimit:200};
 });
 await test('real browser worker malformed input, duplicate flood, capacity lifecycle and reopen',async()=>assert.equal(report.invalidCases,11));
 // Load the same compiled engine in a real browser worker; inject storage write failures only.
 const faults=await page.evaluate(async(base)=>{const source=`importScripts('${base}/moolbase.js');onmessage=async()=>{try{const m=await createMoolBase({locateFile:p=>'${base}/'+p});const call=(name,args=[])=>JSON.parse(m.ccall(name,'string',name==='demo_reset'?['string','string']:name==='demo_add'?['string','string','string','number','string','number','string']:[],args));let cases=0;for(const partial of [false,true]){call('demo_reset',['A','B']);const before=call('demo_add',['old','original','source',0,'support',1,'']);const original=m.FS.write;let triggered=false;m.FS.write=function(stream,buffer,offset,length,position,...rest){if(stream.path.endsWith('graphene.wal')){triggered=true;if(partial){original.call(this,stream,buffer,offset,Math.min(length,24),position,...rest);}throw new m.FS.ErrnoError(28);}return original.call(this,stream,buffer,offset,length,position,...rest);};const failed=call('demo_add',['new','replacement','other',1,'supersede',1,'old']);m.FS.write=original;const after=call('demo_reopen');if(!triggered||failed.ok||after.bundleHash!==before.bundleHash||after.snapshot!==before.snapshot||after.evidence[0].state!=='active'||after.evidence.length!==1)throw Error('failed replacement corrupted original '+JSON.stringify({partial,triggered,failed,after,before}));const retry=call('demo_add',['new','replacement','other',1,'supersede',1,'old']);if(!retry.ok)throw Error('retry failed');cases++;}postMessage({cases});}catch(e){postMessage({error:e.stack});}};`;return new Promise(resolve=>{const w=new Worker(URL.createObjectURL(new Blob([source],{type:'text/javascript'})));w.onmessage=e=>{w.terminate();resolve(e.data)};w.postMessage({});});},url);
 await test('real browser WASM supersession rollback before write and after partial WAL write',async()=>{assert.equal(faults.error,undefined,faults.error);assert.equal(faults.cases,2)});
 await page.close();console.log(JSON.stringify({checks,results,worker:report,storageFaultCases:faults.cases,browser:browser.version()},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));}
